#!/bin/bash
AXIS_HOME=/var/app/tomcat/webapps/webservices/WEB-INF
AXIS_LIB=$AXIS_HOME/lib
AXISCLASSPATH=$AXIS_LIB/axis.jar:$AXIS_LIB/commons-discovery.jar:$AXIS_LIB/commons-logging.jar:$AXIS_LIB/jaxrpc.jar:$AXIS_LIB/saaj.jar:$AXIS_LIB/log4j-1.2.8.jar:$AXIS_LIB/xml-apis.jar:$AXIS_LIB/xercesImpl.jar
export AXIS_HOME; export AXIS_LIB; export AXISCLASSPATH
/usr/java/bin/java -cp $AXISCLASSPATH org.apache.axis.client.AdminClient -ddd -lhttps://jl.mind.unm.edu/webservices/services $1